class_name: src.fetch_data.synthetic.DataLoader
params:
  n_samples: 10000
  configuration:
    'a-c':
      selection: 0.25
      class: 1
    'd-f':
      selection: 0.25
      class: 0
  separator: '-'
  sequence_elements:
    - a
    - b
    - c
    - d
    - e
    - f
    - g
    - h
    - i
    - j