class_name: src.fetch_data.synthetic.DataLoader
params:
  n_samples: 20000
  id_column: '%id_column%'
  event_column: '%event_column%'
  time_column: '%time_column%'
  class_column: '%target_column%'
  configuration:
    'a-b':
      selection: 0.1
      class: 1
    'b-c':
      selection: 0.1
      class: 1
    'c-d':
      selection: 0.1
      class: 1
    'd-e':
      selection: 0.1
      class: 1
    'f-g':
      selection: 0.1
      class: 0
    'g-h':
      selection: 0.1
      class: 0
    'h-i':
      selection: 0.1
      class: 0
    'i-j':
      selection: 0.1
      class: 0
  separator: '-'
  sequence_elements:
    - a
    - b
    - c
    - d
    - e
    - f
    - g
    - h
    - i
    - j
    - k
    - l
    - m
    - n
    - o