class_name: src.fetch_data.synthetic.SyntheticDatasets
params:
  static_only: False
  static_dataset:
    class_name: src.fetch_data.synthetic.StaticDataset
    params:
      n_samples: 20000
      flip_y: 0.2
      random_seed: 42
  time_series_positive:
    class_name: src.fetch_data.synthetic.TimeSeriesDataset
    params:
      event_generator:
        class_name: src.fetch_data.synthetic.EventGenerator
        params:
          max_events: 10
      sequence_generator:
        class_name: src.fetch_data.synthetic.SequenceGenerator
        params:
          n_sequences: 10000
          max_sequence_length: 10
          sequence_weights_splitting_char: '_'
          sequence_weights:
            'a_c': 0.5
          sequences_to_ignore:
            - 'd_f'
  time_series_negative:
    class_name: src.fetch_data.synthetic.TimeSeriesDataset
    params:
      event_generator:
        class_name: src.fetch_data.synthetic.EventGenerator
        params:
          max_events: 10
      sequence_generator:
        class_name: src.fetch_data.synthetic.SequenceGenerator
        params:
          n_sequences: 10000
          max_sequence_length: 10
          sequence_weights_splitting_char: '_'
          sequence_weights:
            'd_f': 0.5
          sequences_to_ignore:
            - 'a_c'