class_name: src.model.sklearn_models.SklearnModel
params:
  model: 'xgboost.XGBClassifier'
  params:
    n_estimators: 39
    max_depth: 9
    learning_rate: 0.8499915306125754
    objective: "binary:logistic"