class_name: src.model.sklearn_models.SklearnModel
params:
  model: 'xgboost.XGBClassifier'
  params:
    n_estimators: 44
    max_depth: 4
    learning_rate: 0.7226013085309871
    objective: "binary:logistic"