class_name: src.model.sklearn_models.SklearnModel
params:
  model: 'xgboost.XGBClassifier'
  params:
    n_estimators: 50
    max_depth: 3
    learning_rate: 0.4441399732618896
    objective: "binary:logistic"