target_column:
  placeholder: '%target_column%'
  value: "label"
id_column:
  placeholder: '%id_column%'
  value: 'session_id'
time_column:
  placeholder: '%time_column%'
  value: 'time'
event_column:
  placeholder: '%event_column%'
  value: 'product_action'