target_column:
  placeholder: '%target_column%'
  value: "malware"
id_column:
  placeholder: '%id_column%'
  value: 'id'
time_column:
  placeholder: '%time_column%'
  value: 'time'
event_column:
  placeholder: '%event_column%'
  value: 'value'