target_column:
  placeholder: '%target_column%'
  value: "class_column"
id_column:
  placeholder: '%id_column%'
  value: 'id_column'
time_column:
  placeholder: '%time_column%'
  value: 'time_column'
event_column:
  placeholder: '%event_column%'
  value: 'event_column'