class_name: src.preprocess.preprocessor.FeatureMaker
params:
  extractor:
    class_name: src.preprocess.extraction.lstm_sequence.LSTMSequence
    params:
  selector:
    class_name: src.preprocess.selection.identity.FeatureIdentity
    params:
      n_features: null
