class_name: src.preprocess.preprocessor.FeatureMaker
params:
  target_column: '%target_column%'
  extractor:
    class_name: src.preprocess.extraction.lstm_sequence.LSTMSequence
    params:
      id_column: '%id_column%'
      feature_column: '%event_column%'
      target_column: '%target_column%'
      time_column: '%time_column%'
  selector:
    class_name: src.preprocess.selection.identity.FeatureIdentity
    params:
      n_features: null
