class_name: src.preprocess.preprocessor.Preprocessor
params:
  steps:
    '1':
      class_name: src.preprocess.onehot.OneHotEncoder
      params:
        id_column: '%id_column%'
        feature_column: '%event_column%'
        target_column: '%target_column%'
    '2':
      class_name: src.preprocess.boruta.BorutaFeatSelection
      params:
        target_column: '%target_column%'
        n_features: null