class_name: src.preprocess.preprocessor.Preprocessor
params:
  steps:
    '0':
      class_name: src.preprocess.onehot.OneHotEncoder
      params:
        id_column: 'id'
        feature_column: 'value'
        target_column: 'malware'
    '1':
      class_name: src.preprocess.boruta.BorutaFeatSelection
      params:
        target_column: 'malware'
        n_features: null
    '2':
      class_name: src.preprocess.train_test_split.TrainTestSplit
      params:
        target_name: 'malware'
        split_type: 'random_stratified'
        test_size: 0.2
        random_state: 42
    
