class_name: src.preprocess.preprocessor.Preprocessor
params:
  steps:
    '0':
      class_name: src.preprocess.onehot.OneHotEncoder
      params:
        id_column: 'id'
        feature_column: 'value'
    '2':
      class_name: src.preprocess.train_test_split.TrainTestSplit
      params:
        target_name: 'malware'
        split_type: 'column_based'
        split_col: 'id'
        test_size: 0.2
        random_state: 42
    '3':
      class_name: src.preprocess.excluder.ColumnExcluder
      params:
        columns:
          - id
