class_name: src.preprocess.preprocessor.Preprocessor
params:
  steps:
    '0':
      class_name: src.preprocess.ts_feature_selection.CausalRuleFeatureSelector
      params:
        repetitions: 5
        n_features: null
        treatment_attr_name: 'malware'
        treatment_attr_value: '1'
        splitting_symbol: " --> "
        ts_id_columns:
          - 'id'
        ts_event_column: 'value'
        ts_datetime_column: 'time'
        prefixspan_config:
          class_name: 'src.preprocess.ts_feature_selection.PrefixSpan'
          params:
            id_columns: [ 'id' ]
            event_column: 'value'
            timestamp_column: time
            rule_max_length: 999
            rule_min_length: 1
            separator: " --> "
            itertool_threshold: 3
        multitesting:
          method: 'bonferroni'
        key_in_result_dict: 'data'
        keep_class: True
    '1':
      class_name: src.preprocess.train_test_split.TrainTestSplit
      params:
        target_name: 'malware'
        split_type: 'random_stratified'
        split_col: 'id'
        test_size: 0.2
        random_state: 42