class_name: src.preprocess.preprocessor.Preprocessor
params:
  steps:
    '0':
      class_name: src.preprocess.onehot.OneHotEncoder
      params:
        id_column: 'id'
        feature_column: 'value'
        target_column: 'malware'