class_name: src.preprocess.preprocessor.FeatureMaker
params:
  extractor:
    class_name: src.preprocess.extraction.onehot.OneHotEncoder
    params:
      id_column: '%id_column%'
      feature_column: '%event_column%'
      target_column: '%target_column%'
  selector:
    class_name: src.preprocess.selection.mutual_info.MutInfoFeatSelection
    params:
      target_column: '%target_column%'
      n_features: null
