class_name: src.preprocess.preprocessor.FeatureMaker
params:
  extractor:
    class_name: src.preprocess.extraction.onehot.OneHotEncoder
    params:
  selector:
    class_name: src.preprocess.selection.random_forest.RFFeatSelection
    params:
      n_features:
