class_name: src.preprocess.preprocessor.FeatureMaker
params:
  target_column: '%target_column%'
  extractor:
    class_name: src.preprocess.extraction.spm.SPM
    params:
      id_columns: 
        - '%id_column%'
      event_column: '%event_column%'
      time_column: '%time_column%'
      target_column: '%target_column%'
      itertool_threshold: 3
  selector:
    class_name: src.preprocess.selection.random_forest.RFFeatSelection
    params:
      target_column: '%target_column%'
      n_features: null
