class_name: src.preprocess.preprocessor.Preprocessor
params:
  steps:
    '0':
      class_name: src.preprocess.labelling.LabelingFromStatic
      params:
        id_column_static: 'id_column'
        id_column_event: 'id_column'
        target_column_static: 'target'
    '1':
      class_name: src.preprocess.ts_feature_selection.CausalRuleFeatureSelector
      params:
        repetitions: 5
        treatment_attr_name: 'target'
        treatment_attr_value: '1'
        splitting_symbol: " --> "
        ts_id_columns:
          - 'id_column'
        ts_event_column: 'event_column'
        ts_datetime_column: 'timestamp'
        prefixspan_config:
          class_name: 'src.preprocess.ts_feature_selection.PrefixSpan'
          params:
            id_columns: [ 'id_column']
            event_column: 'event_column'
            timestamp_column: eventtime
            rule_max_length: 999
            rule_min_length: 1
            separator: " --> "
            itertool_threshold: 5
        multitesting:
          method: 'bonferroni'
    '2':
      class_name: src.preprocess.merge.Merger
      params:
        dataset_left_config:
          class_name: src.preprocess.merge.MergeDatasetConfig
          params:
            merge_on: "id_column"
            ignore_columns:
            keep_columns:
        dataset_right_config:
          class_name: src.preprocess.merge.MergeDatasetConfig
          params:
            merge_on: "id_column"
            ignore_columns:
            keep_columns:
        n_rows:
        how: 'right'
        filename_merge: synthetic\merge_data.parquet
        merge_params:
        override: True
        save: False
    '3':
      class_name: src.preprocess.train_test_split.TrainTestSplit
      params:
        target_name: 'target'
        split_type: 'column_based'
        split_col: 'id_column'
        test_size: 0.2
        random_state: 42
    '4':
      class_name: src.preprocess.excluder.ColumnExcluder
      params:
        columns:
          - index
          - id_column
