class_name: src.preprocess.preprocessor.Preprocessor
params:
  steps:
    '1':
      class_name: src.preprocess.onehot.OneHotEncoder
      params:
        id_column: 'id_column'
        feature_column: 'event_column'
        target_column: 'target'
    '2':
      class_name: src.preprocess.random_forest.RFFeatSelection
      params:
        target_column: 'target'
        n_features: null
