class_name: src.preprocess.preprocessor.Preprocessor
params:
  steps:
    '0':
      class_name: src.preprocess.labelling.LabelingFromStatic
      params:
        id_column_static: 'id_column'
        id_column_event: 'id_column'
        target_column_static: 'target'
    '1':
      class_name: src.preprocess.onehot.OneHotEncoder
      params:
        id_column: 'id_column'
        feature_column: 'event_column'
        target_column: 'target'
    '2':
      class_name: src.preprocess.random_forest.RFFeatSelection
      params:
        target_column: 'target'
        n_features: null
